export type { ConfirmAddInstructorDialogProps } from "./confirm-add-dialog";
export { ConfirmAddInstructorDialog } from "./confirm-add-dialog";
export type { InstructorApprovalActionsProps } from "./instructor-approval-actions";
export { InstructorApprovalActions } from "./instructor-approval-actions";
export type { InstructorCourseEditorRouteProps } from "./instructor-course-editor-route";
export { renderInstructorCourseEditorRoute } from "./instructor-course-editor-route";
export type { InstructorListPaginationProps } from "./instructor-list-pagination";
export { InstructorListPagination } from "./instructor-list-pagination";
export type { InstructorProfileViewDialogProps } from "./instructor-profile-view-dialog";
export { InstructorProfileViewDialog } from "./instructor-profile-view-dialog";
